fn main() {
    // Build the app
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .codegen(tauri_build::CodegenContext::new())
            .plugin(
                "app-menu",
                tauri_build::InlinedPlugin::new().commands(&["show", "hide", "show_window"]),
            )
            .plugin(
                "config",
                tauri_build::InlinedPlugin::new().commands(&[
                    "get_storage_dir",
                    "get_config",
                    "set_config",
                ]),
            )
            .plugin(
                "cover",
                tauri_build::InlinedPlugin::new().commands(&["get_cover"]),
            )
            .plugin(
                "desktop-lyrics",
                tauri_build::InlinedPlugin::new().commands(&[
                    "open",
                    "sync_state",
                    "get_state",
                    "close",
                    "start_dragging",
                    "control",
                    "set_mouse_passthrough",
                    "get_window_geometry",
                    "update_window_geometry",
                    "set_always_on_top",
                    "set_resizable",
                ]),
            )
            .plugin(
                "lyrics",
                tauri_build::InlinedPlugin::new()
                    .commands(&["get_sibling_lyrics", "select_and_read"]),
            )
            .plugin(
                "tray",
                tauri_build::InlinedPlugin::new().commands(&["sync_state"]),
            )
            .plugin(
                "database",
                tauri_build::InlinedPlugin::new().commands(&[
                    "scan_library",
                    "get_all_tracks",
                    "remove_tracks",
                    "get_tracks",
                    "get_track",
                    "update_track",
                    "get_artists",
                    "get_artist_tracks",
                    "get_compilation_albums",
                    "has_compilations",
                    "get_all_playlists",
                    "get_playlist",
                    "create_playlist",
                    "rename_playlist",
                    "set_playlist_tracks",
                    "export_playlist",
                    "delete_playlist",
                    "reset",
                ]),
            )
            .plugin(
                "default-view",
                tauri_build::InlinedPlugin::new().commands(&["set"]),
            )
            .plugin(
                "media-controls",
                tauri_build::InlinedPlugin::new().commands(&[
                    "set_metadata",
                    "set_playback",
                    "clear",
                ]),
            )
            .plugin(
                "native-audio",
                tauri_build::InlinedPlugin::new().commands(&[
                    "load",
                    "play",
                    "pause",
                    "seek",
                    "get_state",
                    "set_volume",
                    "set_playback_rate",
                    "stop",
                ]),
            )
            .plugin(
                "sleepblocker",
                tauri_build::InlinedPlugin::new().commands(&["enable", "disable"]),
            ),
    )
    .expect("Failed to run tauri-build");
}
